# Generated by Django 2.2.24 on 2021-11-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irismodel',
            name='petal_length',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='irismodel',
            name='petal_width',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='irismodel',
            name='sepal_length',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='irismodel',
            name='sepal_width',
            field=models.FloatField(max_length=255),
        ),
    ]
