# Generated by Django 2.2.24 on 2021-11-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20211119_0943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IrisModel',
        ),
    ]
