# Generated by Django 2.2.24 on 2021-11-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_app', '0003_delete_irismodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrisModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.FloatField(verbose_name='sepal_length')),
                ('sepal_width', models.FloatField(verbose_name='sepal_width')),
                ('petal_length', models.FloatField(verbose_name='petal_length')),
                ('petal_width', models.FloatField(verbose_name='petal_width')),
                ('iris_class', models.CharField(max_length=255, verbose_name='iris_class')),
            ],
        ),
    ]
